### ISSUE TITLE
Checklist #1

### ISSUE THREAD

**Issue by nebbles** [nebbles/de2-gizmo-sound#1]
- [x] Read the Gizmo student handbook (available via Blackboard)
- [x] Familiarise yourself with the Autumn term syllabus, group assignment and assessment criteria (Gizmo student handbook, pp 15 & 20 - 22)
- [x] Read the workflow tips (Gizmo student handbook p18)
- [x] Check out the resources section of the Gizmo student handbook, especially the themed inspiration links, p26 
- [x] Refresh your understanding of DE1-EA1.3 Electrical Electronic Engineering, esp. lectures 1, 2, 7, 17 and 20.
- [x] Set up Raspberry Pi (including "advance remote connection” - all detailed in Lab 1, see Blackboard)
- [x] Understand content of lectures 2 & 3 (available via Blackboard). Lecture 2 is just pictures so you only need to familiarise yourself with the names of machine elements there.
- [x] Update to latest version of SolidWorks and ensure it’s running
