### ISSUE TITLE
Checklist #2

### ISSUE THREAD

**Issue by nebbles** [nebbles/de2-gizmo-sound#2]
- [x] Connect with you team members (lists attached and available via Blackboard). Establish schedule, team working times, group management.
- [x] Get inspired, start generating concepts 
- [x] Work through content of Lab 2 - RPi GPIO. Aim to do this before next Thursday. Do this in your pairs or allocated groups of four. I shall give you hardware in Thursday’s lecture.
- [x] Bring your laptop with SolidWorks for next week’s lab, Lab 3 - SolidWorks Motion simulation  
- [x] Install the Pure Data Vanilla distribution for Lab 4 - Pure Data.  You can find the installers at the following links:
  - For Windows: http://msp.ucsd.edu/Software/pd-0.47-1.windows-installer.exe
  - For MacOS (the following link is for the 32-bits version - it's important that you install this and not the 64-bits version, as some of the tools we'll use won't work on the 64-bits one): http://msp.ucsd.edu/Software/pd-0.47-1.mac.tar.gz
